#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_BENHVIEN")]
	public partial class QLBVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBENH(BENH instance);
    partial void UpdateBENH(BENH instance);
    partial void DeleteBENH(BENH instance);
    partial void InsertTOATHUOC(TOATHUOC instance);
    partial void UpdateTOATHUOC(TOATHUOC instance);
    partial void DeleteTOATHUOC(TOATHUOC instance);
    partial void InsertBENHNHAN(BENHNHAN instance);
    partial void UpdateBENHNHAN(BENHNHAN instance);
    partial void DeleteBENHNHAN(BENHNHAN instance);
    partial void InsertCHITIETBACSI(CHITIETBACSI instance);
    partial void UpdateCHITIETBACSI(CHITIETBACSI instance);
    partial void DeleteCHITIETBACSI(CHITIETBACSI instance);
    partial void InsertCHITIETCHUANDOAN(CHITIETCHUANDOAN instance);
    partial void UpdateCHITIETCHUANDOAN(CHITIETCHUANDOAN instance);
    partial void DeleteCHITIETCHUANDOAN(CHITIETCHUANDOAN instance);
    partial void InsertCHITIETHOCVI(CHITIETHOCVI instance);
    partial void UpdateCHITIETHOCVI(CHITIETHOCVI instance);
    partial void DeleteCHITIETHOCVI(CHITIETHOCVI instance);
    partial void InsertCHITIETTOATHUOC(CHITIETTOATHUOC instance);
    partial void UpdateCHITIETTOATHUOC(CHITIETTOATHUOC instance);
    partial void DeleteCHITIETTOATHUOC(CHITIETTOATHUOC instance);
    partial void InsertHOCVI(HOCVI instance);
    partial void UpdateHOCVI(HOCVI instance);
    partial void DeleteHOCVI(HOCVI instance);
    partial void InsertLICHLAMVIEC(LICHLAMVIEC instance);
    partial void UpdateLICHLAMVIEC(LICHLAMVIEC instance);
    partial void DeleteLICHLAMVIEC(LICHLAMVIEC instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUHEN(PHIEUHEN instance);
    partial void UpdatePHIEUHEN(PHIEUHEN instance);
    partial void DeletePHIEUHEN(PHIEUHEN instance);
    partial void InsertPHIEUKHAM(PHIEUKHAM instance);
    partial void UpdatePHIEUKHAM(PHIEUKHAM instance);
    partial void DeletePHIEUKHAM(PHIEUKHAM instance);
    partial void InsertPHONGKHAM(PHONGKHAM instance);
    partial void UpdatePHONGKHAM(PHONGKHAM instance);
    partial void DeletePHONGKHAM(PHONGKHAM instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHUOC(THUOC instance);
    partial void UpdateTHUOC(THUOC instance);
    partial void DeleteTHUOC(THUOC instance);
    #endregion
		
		public QLBVDataContext() : 
				base(global::DAL.Properties.Settings.Default.QL_BENHVIENConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLBVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BENH> BENHs
		{
			get
			{
				return this.GetTable<BENH>();
			}
		}
		
		public System.Data.Linq.Table<TOATHUOC> TOATHUOCs
		{
			get
			{
				return this.GetTable<TOATHUOC>();
			}
		}
		
		public System.Data.Linq.Table<BENHNHAN> BENHNHANs
		{
			get
			{
				return this.GetTable<BENHNHAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETBACSI> CHITIETBACSIs
		{
			get
			{
				return this.GetTable<CHITIETBACSI>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETCHUANDOAN> CHITIETCHUANDOANs
		{
			get
			{
				return this.GetTable<CHITIETCHUANDOAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHOCVI> CHITIETHOCVIs
		{
			get
			{
				return this.GetTable<CHITIETHOCVI>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETTOATHUOC> CHITIETTOATHUOCs
		{
			get
			{
				return this.GetTable<CHITIETTOATHUOC>();
			}
		}
		
		public System.Data.Linq.Table<HOCVI> HOCVIs
		{
			get
			{
				return this.GetTable<HOCVI>();
			}
		}
		
		public System.Data.Linq.Table<LICHLAMVIEC> LICHLAMVIECs
		{
			get
			{
				return this.GetTable<LICHLAMVIEC>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUHEN> PHIEUHENs
		{
			get
			{
				return this.GetTable<PHIEUHEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUKHAM> PHIEUKHAMs
		{
			get
			{
				return this.GetTable<PHIEUKHAM>();
			}
		}
		
		public System.Data.Linq.Table<PHONGKHAM> PHONGKHAMs
		{
			get
			{
				return this.GetTable<PHONGKHAM>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THUOC> THUOCs
		{
			get
			{
				return this.GetTable<THUOC>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BENH")]
	public partial class BENH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MABENH;
		
		private string _TENBENH;
		
		private EntitySet<CHITIETCHUANDOAN> _CHITIETCHUANDOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABENHChanging(string value);
    partial void OnMABENHChanged();
    partial void OnTENBENHChanging(string value);
    partial void OnTENBENHChanged();
    #endregion
		
		public BENH()
		{
			this._CHITIETCHUANDOANs = new EntitySet<CHITIETCHUANDOAN>(new Action<CHITIETCHUANDOAN>(this.attach_CHITIETCHUANDOANs), new Action<CHITIETCHUANDOAN>(this.detach_CHITIETCHUANDOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABENH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABENH
		{
			get
			{
				return this._MABENH;
			}
			set
			{
				if ((this._MABENH != value))
				{
					this.OnMABENHChanging(value);
					this.SendPropertyChanging();
					this._MABENH = value;
					this.SendPropertyChanged("MABENH");
					this.OnMABENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBENH", DbType="NVarChar(30)")]
		public string TENBENH
		{
			get
			{
				return this._TENBENH;
			}
			set
			{
				if ((this._TENBENH != value))
				{
					this.OnTENBENHChanging(value);
					this.SendPropertyChanging();
					this._TENBENH = value;
					this.SendPropertyChanged("TENBENH");
					this.OnTENBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENH_CHITIETCHUANDOAN", Storage="_CHITIETCHUANDOANs", ThisKey="MABENH", OtherKey="MABENH")]
		public EntitySet<CHITIETCHUANDOAN> CHITIETCHUANDOANs
		{
			get
			{
				return this._CHITIETCHUANDOANs;
			}
			set
			{
				this._CHITIETCHUANDOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETCHUANDOANs(CHITIETCHUANDOAN entity)
		{
			this.SendPropertyChanging();
			entity.BENH = this;
		}
		
		private void detach_CHITIETCHUANDOANs(CHITIETCHUANDOAN entity)
		{
			this.SendPropertyChanging();
			entity.BENH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOATHUOC")]
	public partial class TOATHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOATHUOC;
		
		private string _MAPHIEUKHAM;
		
		private string _MANHANVIEN;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private System.Nullable<int> _TONGTIEN;
		
		private string _LOIDAN;
		
		private EntitySet<CHITIETCHUANDOAN> _CHITIETCHUANDOANs;
		
		private EntitySet<CHITIETTOATHUOC> _CHITIETTOATHUOCs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<PHIEUKHAM> _PHIEUKHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOATHUOCChanging(string value);
    partial void OnMATOATHUOCChanged();
    partial void OnMAPHIEUKHAMChanging(string value);
    partial void OnMAPHIEUKHAMChanged();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnTONGTIENChanging(System.Nullable<int> value);
    partial void OnTONGTIENChanged();
    partial void OnLOIDANChanging(string value);
    partial void OnLOIDANChanged();
    #endregion
		
		public TOATHUOC()
		{
			this._CHITIETCHUANDOANs = new EntitySet<CHITIETCHUANDOAN>(new Action<CHITIETCHUANDOAN>(this.attach_CHITIETCHUANDOANs), new Action<CHITIETCHUANDOAN>(this.detach_CHITIETCHUANDOANs));
			this._CHITIETTOATHUOCs = new EntitySet<CHITIETTOATHUOC>(new Action<CHITIETTOATHUOC>(this.attach_CHITIETTOATHUOCs), new Action<CHITIETTOATHUOC>(this.detach_CHITIETTOATHUOCs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._PHIEUKHAM = default(EntityRef<PHIEUKHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOATHUOC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOATHUOC
		{
			get
			{
				return this._MATOATHUOC;
			}
			set
			{
				if ((this._MATOATHUOC != value))
				{
					this.OnMATOATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATOATHUOC = value;
					this.SendPropertyChanged("MATOATHUOC");
					this.OnMATOATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUKHAM", DbType="VarChar(10)")]
		public string MAPHIEUKHAM
		{
			get
			{
				return this._MAPHIEUKHAM;
			}
			set
			{
				if ((this._MAPHIEUKHAM != value))
				{
					if (this._PHIEUKHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUKHAMChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUKHAM = value;
					this.SendPropertyChanged("MAPHIEUKHAM");
					this.OnMAPHIEUKHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="VarChar(10)")]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int")]
		public System.Nullable<int> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOIDAN", DbType="NVarChar(100)")]
		public string LOIDAN
		{
			get
			{
				return this._LOIDAN;
			}
			set
			{
				if ((this._LOIDAN != value))
				{
					this.OnLOIDANChanging(value);
					this.SendPropertyChanging();
					this._LOIDAN = value;
					this.SendPropertyChanged("LOIDAN");
					this.OnLOIDANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOATHUOC_CHITIETCHUANDOAN", Storage="_CHITIETCHUANDOANs", ThisKey="MATOATHUOC", OtherKey="MATOATHUOC")]
		public EntitySet<CHITIETCHUANDOAN> CHITIETCHUANDOANs
		{
			get
			{
				return this._CHITIETCHUANDOANs;
			}
			set
			{
				this._CHITIETCHUANDOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOATHUOC_CHITIETTOATHUOC", Storage="_CHITIETTOATHUOCs", ThisKey="MATOATHUOC", OtherKey="MATOATHUOC")]
		public EntitySet<CHITIETTOATHUOC> CHITIETTOATHUOCs
		{
			get
			{
				return this._CHITIETTOATHUOCs;
			}
			set
			{
				this._CHITIETTOATHUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TOATHUOC", Storage="_NHANVIEN", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TOATHUOCs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TOATHUOCs.Add(this);
						this._MANHANVIEN = value.MANHANVIEN;
					}
					else
					{
						this._MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUKHAM_TOATHUOC", Storage="_PHIEUKHAM", ThisKey="MAPHIEUKHAM", OtherKey="MAPHIEUKHAM", IsForeignKey=true)]
		public PHIEUKHAM PHIEUKHAM
		{
			get
			{
				return this._PHIEUKHAM.Entity;
			}
			set
			{
				PHIEUKHAM previousValue = this._PHIEUKHAM.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUKHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUKHAM.Entity = null;
						previousValue.TOATHUOCs.Remove(this);
					}
					this._PHIEUKHAM.Entity = value;
					if ((value != null))
					{
						value.TOATHUOCs.Add(this);
						this._MAPHIEUKHAM = value.MAPHIEUKHAM;
					}
					else
					{
						this._MAPHIEUKHAM = default(string);
					}
					this.SendPropertyChanged("PHIEUKHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETCHUANDOANs(CHITIETCHUANDOAN entity)
		{
			this.SendPropertyChanging();
			entity.TOATHUOC = this;
		}
		
		private void detach_CHITIETCHUANDOANs(CHITIETCHUANDOAN entity)
		{
			this.SendPropertyChanging();
			entity.TOATHUOC = null;
		}
		
		private void attach_CHITIETTOATHUOCs(CHITIETTOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.TOATHUOC = this;
		}
		
		private void detach_CHITIETTOATHUOCs(CHITIETTOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.TOATHUOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BENHNHAN")]
	public partial class BENHNHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MABENHNHAN;
		
		private string _TENBENHNHAN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private EntitySet<PHIEUKHAM> _PHIEUKHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABENHNHANChanging(string value);
    partial void OnMABENHNHANChanged();
    partial void OnTENBENHNHANChanging(string value);
    partial void OnTENBENHNHANChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public BENHNHAN()
		{
			this._PHIEUKHAMs = new EntitySet<PHIEUKHAM>(new Action<PHIEUKHAM>(this.attach_PHIEUKHAMs), new Action<PHIEUKHAM>(this.detach_PHIEUKHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABENHNHAN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABENHNHAN
		{
			get
			{
				return this._MABENHNHAN;
			}
			set
			{
				if ((this._MABENHNHAN != value))
				{
					this.OnMABENHNHANChanging(value);
					this.SendPropertyChanging();
					this._MABENHNHAN = value;
					this.SendPropertyChanged("MABENHNHAN");
					this.OnMABENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBENHNHAN", DbType="NVarChar(30)")]
		public string TENBENHNHAN
		{
			get
			{
				return this._TENBENHNHAN;
			}
			set
			{
				if ((this._TENBENHNHAN != value))
				{
					this.OnTENBENHNHANChanging(value);
					this.SendPropertyChanging();
					this._TENBENHNHAN = value;
					this.SendPropertyChanged("TENBENHNHAN");
					this.OnTENBENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENHNHAN_PHIEUKHAM", Storage="_PHIEUKHAMs", ThisKey="MABENHNHAN", OtherKey="MABENHNHAN")]
		public EntitySet<PHIEUKHAM> PHIEUKHAMs
		{
			get
			{
				return this._PHIEUKHAMs;
			}
			set
			{
				this._PHIEUKHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUKHAMs(PHIEUKHAM entity)
		{
			this.SendPropertyChanging();
			entity.BENHNHAN = this;
		}
		
		private void detach_PHIEUKHAMs(PHIEUKHAM entity)
		{
			this.SendPropertyChanging();
			entity.BENHNHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETBACSI")]
	public partial class CHITIETBACSI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MABACSI;
		
		private string _HOCHAM;
		
		private string _GIOITHIEU;
		
		private string _GIOITINH;
		
		private string _HINHANH;
		
		private EntitySet<CHITIETHOCVI> _CHITIETHOCVIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABACSIChanging(string value);
    partial void OnMABACSIChanged();
    partial void OnHOCHAMChanging(string value);
    partial void OnHOCHAMChanged();
    partial void OnGIOITHIEUChanging(string value);
    partial void OnGIOITHIEUChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    #endregion
		
		public CHITIETBACSI()
		{
			this._CHITIETHOCVIs = new EntitySet<CHITIETHOCVI>(new Action<CHITIETHOCVI>(this.attach_CHITIETHOCVIs), new Action<CHITIETHOCVI>(this.detach_CHITIETHOCVIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABACSI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABACSI
		{
			get
			{
				return this._MABACSI;
			}
			set
			{
				if ((this._MABACSI != value))
				{
					this.OnMABACSIChanging(value);
					this.SendPropertyChanging();
					this._MABACSI = value;
					this.SendPropertyChanged("MABACSI");
					this.OnMABACSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCHAM", DbType="NVarChar(50)")]
		public string HOCHAM
		{
			get
			{
				return this._HOCHAM;
			}
			set
			{
				if ((this._HOCHAM != value))
				{
					this.OnHOCHAMChanging(value);
					this.SendPropertyChanging();
					this._HOCHAM = value;
					this.SendPropertyChanged("HOCHAM");
					this.OnHOCHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITHIEU", DbType="NVarChar(MAX)")]
		public string GIOITHIEU
		{
			get
			{
				return this._GIOITHIEU;
			}
			set
			{
				if ((this._GIOITHIEU != value))
				{
					this.OnGIOITHIEUChanging(value);
					this.SendPropertyChanging();
					this._GIOITHIEU = value;
					this.SendPropertyChanged("GIOITHIEU");
					this.OnGIOITHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(MAX)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETBACSI_CHITIETHOCVI", Storage="_CHITIETHOCVIs", ThisKey="MABACSI", OtherKey="MABACSI")]
		public EntitySet<CHITIETHOCVI> CHITIETHOCVIs
		{
			get
			{
				return this._CHITIETHOCVIs;
			}
			set
			{
				this._CHITIETHOCVIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOCVIs(CHITIETHOCVI entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETBACSI = this;
		}
		
		private void detach_CHITIETHOCVIs(CHITIETHOCVI entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETBACSI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETCHUANDOAN")]
	public partial class CHITIETCHUANDOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOATHUOC;
		
		private string _MABENH;
		
		private EntityRef<BENH> _BENH;
		
		private EntityRef<TOATHUOC> _TOATHUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOATHUOCChanging(string value);
    partial void OnMATOATHUOCChanged();
    partial void OnMABENHChanging(string value);
    partial void OnMABENHChanged();
    #endregion
		
		public CHITIETCHUANDOAN()
		{
			this._BENH = default(EntityRef<BENH>);
			this._TOATHUOC = default(EntityRef<TOATHUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOATHUOC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOATHUOC
		{
			get
			{
				return this._MATOATHUOC;
			}
			set
			{
				if ((this._MATOATHUOC != value))
				{
					if (this._TOATHUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATOATHUOC = value;
					this.SendPropertyChanged("MATOATHUOC");
					this.OnMATOATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABENH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABENH
		{
			get
			{
				return this._MABENH;
			}
			set
			{
				if ((this._MABENH != value))
				{
					if (this._BENH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABENHChanging(value);
					this.SendPropertyChanging();
					this._MABENH = value;
					this.SendPropertyChanged("MABENH");
					this.OnMABENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENH_CHITIETCHUANDOAN", Storage="_BENH", ThisKey="MABENH", OtherKey="MABENH", IsForeignKey=true)]
		public BENH BENH
		{
			get
			{
				return this._BENH.Entity;
			}
			set
			{
				BENH previousValue = this._BENH.Entity;
				if (((previousValue != value) 
							|| (this._BENH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BENH.Entity = null;
						previousValue.CHITIETCHUANDOANs.Remove(this);
					}
					this._BENH.Entity = value;
					if ((value != null))
					{
						value.CHITIETCHUANDOANs.Add(this);
						this._MABENH = value.MABENH;
					}
					else
					{
						this._MABENH = default(string);
					}
					this.SendPropertyChanged("BENH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOATHUOC_CHITIETCHUANDOAN", Storage="_TOATHUOC", ThisKey="MATOATHUOC", OtherKey="MATOATHUOC", IsForeignKey=true)]
		public TOATHUOC TOATHUOC
		{
			get
			{
				return this._TOATHUOC.Entity;
			}
			set
			{
				TOATHUOC previousValue = this._TOATHUOC.Entity;
				if (((previousValue != value) 
							|| (this._TOATHUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOATHUOC.Entity = null;
						previousValue.CHITIETCHUANDOANs.Remove(this);
					}
					this._TOATHUOC.Entity = value;
					if ((value != null))
					{
						value.CHITIETCHUANDOANs.Add(this);
						this._MATOATHUOC = value.MATOATHUOC;
					}
					else
					{
						this._MATOATHUOC = default(string);
					}
					this.SendPropertyChanged("TOATHUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOCVI")]
	public partial class CHITIETHOCVI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MABACSI;
		
		private string _MAHOCVI;
		
		private EntityRef<CHITIETBACSI> _CHITIETBACSI;
		
		private EntityRef<HOCVI> _HOCVI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABACSIChanging(string value);
    partial void OnMABACSIChanged();
    partial void OnMAHOCVIChanging(string value);
    partial void OnMAHOCVIChanged();
    #endregion
		
		public CHITIETHOCVI()
		{
			this._CHITIETBACSI = default(EntityRef<CHITIETBACSI>);
			this._HOCVI = default(EntityRef<HOCVI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABACSI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MABACSI
		{
			get
			{
				return this._MABACSI;
			}
			set
			{
				if ((this._MABACSI != value))
				{
					if (this._CHITIETBACSI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABACSIChanging(value);
					this.SendPropertyChanging();
					this._MABACSI = value;
					this.SendPropertyChanged("MABACSI");
					this.OnMABACSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOCVI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOCVI
		{
			get
			{
				return this._MAHOCVI;
			}
			set
			{
				if ((this._MAHOCVI != value))
				{
					if (this._HOCVI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHOCVIChanging(value);
					this.SendPropertyChanging();
					this._MAHOCVI = value;
					this.SendPropertyChanged("MAHOCVI");
					this.OnMAHOCVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETBACSI_CHITIETHOCVI", Storage="_CHITIETBACSI", ThisKey="MABACSI", OtherKey="MABACSI", IsForeignKey=true)]
		public CHITIETBACSI CHITIETBACSI
		{
			get
			{
				return this._CHITIETBACSI.Entity;
			}
			set
			{
				CHITIETBACSI previousValue = this._CHITIETBACSI.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETBACSI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETBACSI.Entity = null;
						previousValue.CHITIETHOCVIs.Remove(this);
					}
					this._CHITIETBACSI.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOCVIs.Add(this);
						this._MABACSI = value.MABACSI;
					}
					else
					{
						this._MABACSI = default(string);
					}
					this.SendPropertyChanged("CHITIETBACSI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCVI_CHITIETHOCVI", Storage="_HOCVI", ThisKey="MAHOCVI", OtherKey="MAHOCVI", IsForeignKey=true)]
		public HOCVI HOCVI
		{
			get
			{
				return this._HOCVI.Entity;
			}
			set
			{
				HOCVI previousValue = this._HOCVI.Entity;
				if (((previousValue != value) 
							|| (this._HOCVI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCVI.Entity = null;
						previousValue.CHITIETHOCVIs.Remove(this);
					}
					this._HOCVI.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOCVIs.Add(this);
						this._MAHOCVI = value.MAHOCVI;
					}
					else
					{
						this._MAHOCVI = default(string);
					}
					this.SendPropertyChanged("HOCVI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETTOATHUOC")]
	public partial class CHITIETTOATHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOATHUOC;
		
		private string _MATHUOC;
		
		private System.Nullable<int> _DONGIA;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _GHICHU;
		
		private EntityRef<TOATHUOC> _TOATHUOC;
		
		private EntityRef<THUOC> _THUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOATHUOCChanging(string value);
    partial void OnMATOATHUOCChanged();
    partial void OnMATHUOCChanging(string value);
    partial void OnMATHUOCChanged();
    partial void OnDONGIAChanging(System.Nullable<int> value);
    partial void OnDONGIAChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public CHITIETTOATHUOC()
		{
			this._TOATHUOC = default(EntityRef<TOATHUOC>);
			this._THUOC = default(EntityRef<THUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOATHUOC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOATHUOC
		{
			get
			{
				return this._MATOATHUOC;
			}
			set
			{
				if ((this._MATOATHUOC != value))
				{
					if (this._TOATHUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATOATHUOC = value;
					this.SendPropertyChanged("MATOATHUOC");
					this.OnMATOATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUOC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUOC
		{
			get
			{
				return this._MATHUOC;
			}
			set
			{
				if ((this._MATHUOC != value))
				{
					if (this._THUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATHUOC = value;
					this.SendPropertyChanged("MATHUOC");
					this.OnMATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Int")]
		public System.Nullable<int> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(100)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOATHUOC_CHITIETTOATHUOC", Storage="_TOATHUOC", ThisKey="MATOATHUOC", OtherKey="MATOATHUOC", IsForeignKey=true)]
		public TOATHUOC TOATHUOC
		{
			get
			{
				return this._TOATHUOC.Entity;
			}
			set
			{
				TOATHUOC previousValue = this._TOATHUOC.Entity;
				if (((previousValue != value) 
							|| (this._TOATHUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOATHUOC.Entity = null;
						previousValue.CHITIETTOATHUOCs.Remove(this);
					}
					this._TOATHUOC.Entity = value;
					if ((value != null))
					{
						value.CHITIETTOATHUOCs.Add(this);
						this._MATOATHUOC = value.MATOATHUOC;
					}
					else
					{
						this._MATOATHUOC = default(string);
					}
					this.SendPropertyChanged("TOATHUOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CHITIETTOATHUOC", Storage="_THUOC", ThisKey="MATHUOC", OtherKey="MATHUOC", IsForeignKey=true)]
		public THUOC THUOC
		{
			get
			{
				return this._THUOC.Entity;
			}
			set
			{
				THUOC previousValue = this._THUOC.Entity;
				if (((previousValue != value) 
							|| (this._THUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUOC.Entity = null;
						previousValue.CHITIETTOATHUOCs.Remove(this);
					}
					this._THUOC.Entity = value;
					if ((value != null))
					{
						value.CHITIETTOATHUOCs.Add(this);
						this._MATHUOC = value.MATHUOC;
					}
					else
					{
						this._MATHUOC = default(string);
					}
					this.SendPropertyChanged("THUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCVI")]
	public partial class HOCVI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHOCVI;
		
		private string _TENHOCVI;
		
		private System.Nullable<int> _BACHOCVI;
		
		private EntitySet<CHITIETHOCVI> _CHITIETHOCVIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOCVIChanging(string value);
    partial void OnMAHOCVIChanged();
    partial void OnTENHOCVIChanging(string value);
    partial void OnTENHOCVIChanged();
    partial void OnBACHOCVIChanging(System.Nullable<int> value);
    partial void OnBACHOCVIChanged();
    #endregion
		
		public HOCVI()
		{
			this._CHITIETHOCVIs = new EntitySet<CHITIETHOCVI>(new Action<CHITIETHOCVI>(this.attach_CHITIETHOCVIs), new Action<CHITIETHOCVI>(this.detach_CHITIETHOCVIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOCVI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOCVI
		{
			get
			{
				return this._MAHOCVI;
			}
			set
			{
				if ((this._MAHOCVI != value))
				{
					this.OnMAHOCVIChanging(value);
					this.SendPropertyChanging();
					this._MAHOCVI = value;
					this.SendPropertyChanged("MAHOCVI");
					this.OnMAHOCVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHOCVI", DbType="NVarChar(50)")]
		public string TENHOCVI
		{
			get
			{
				return this._TENHOCVI;
			}
			set
			{
				if ((this._TENHOCVI != value))
				{
					this.OnTENHOCVIChanging(value);
					this.SendPropertyChanging();
					this._TENHOCVI = value;
					this.SendPropertyChanged("TENHOCVI");
					this.OnTENHOCVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACHOCVI", DbType="Int")]
		public System.Nullable<int> BACHOCVI
		{
			get
			{
				return this._BACHOCVI;
			}
			set
			{
				if ((this._BACHOCVI != value))
				{
					this.OnBACHOCVIChanging(value);
					this.SendPropertyChanging();
					this._BACHOCVI = value;
					this.SendPropertyChanged("BACHOCVI");
					this.OnBACHOCVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCVI_CHITIETHOCVI", Storage="_CHITIETHOCVIs", ThisKey="MAHOCVI", OtherKey="MAHOCVI")]
		public EntitySet<CHITIETHOCVI> CHITIETHOCVIs
		{
			get
			{
				return this._CHITIETHOCVIs;
			}
			set
			{
				this._CHITIETHOCVIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOCVIs(CHITIETHOCVI entity)
		{
			this.SendPropertyChanging();
			entity.HOCVI = this;
		}
		
		private void detach_CHITIETHOCVIs(CHITIETHOCVI entity)
		{
			this.SendPropertyChanging();
			entity.HOCVI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LICHLAMVIEC")]
	public partial class LICHLAMVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALICH;
		
		private string _MANHANVIEN;
		
		private System.Nullable<System.DateTime> _NGAYLAM;
		
		private string _CALAM;
		
		private string _PHONGLAMVIEC;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALICHChanging(string value);
    partial void OnMALICHChanged();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    partial void OnNGAYLAMChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAMChanged();
    partial void OnCALAMChanging(string value);
    partial void OnCALAMChanged();
    partial void OnPHONGLAMVIECChanging(string value);
    partial void OnPHONGLAMVIECChanged();
    #endregion
		
		public LICHLAMVIEC()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALICH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALICH
		{
			get
			{
				return this._MALICH;
			}
			set
			{
				if ((this._MALICH != value))
				{
					this.OnMALICHChanging(value);
					this.SendPropertyChanging();
					this._MALICH = value;
					this.SendPropertyChanged("MALICH");
					this.OnMALICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="VarChar(10)")]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAM", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAM
		{
			get
			{
				return this._NGAYLAM;
			}
			set
			{
				if ((this._NGAYLAM != value))
				{
					this.OnNGAYLAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAM = value;
					this.SendPropertyChanged("NGAYLAM");
					this.OnNGAYLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALAM", DbType="NVarChar(5)")]
		public string CALAM
		{
			get
			{
				return this._CALAM;
			}
			set
			{
				if ((this._CALAM != value))
				{
					this.OnCALAMChanging(value);
					this.SendPropertyChanging();
					this._CALAM = value;
					this.SendPropertyChanged("CALAM");
					this.OnCALAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONGLAMVIEC", DbType="VarChar(10)")]
		public string PHONGLAMVIEC
		{
			get
			{
				return this._PHONGLAMVIEC;
			}
			set
			{
				if ((this._PHONGLAMVIEC != value))
				{
					this.OnPHONGLAMVIECChanging(value);
					this.SendPropertyChanging();
					this._PHONGLAMVIEC = value;
					this.SendPropertyChanged("PHONGLAMVIEC");
					this.OnPHONGLAMVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LICHLAMVIEC", Storage="_NHANVIEN", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.LICHLAMVIECs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.LICHLAMVIECs.Add(this);
						this._MANHANVIEN = value.MANHANVIEN;
					}
					else
					{
						this._MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANVIEN;
		
		private string _TENNHANVIEN;
		
		private string _CHUCVU;
		
		private string _MATAIKHOAN;
		
		private EntitySet<TOATHUOC> _TOATHUOCs;
		
		private EntitySet<LICHLAMVIEC> _LICHLAMVIECs;
		
		private EntitySet<PHIEUHEN> _PHIEUHENs;
		
		private EntitySet<PHIEUKHAM> _PHIEUKHAMs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    partial void OnTENNHANVIENChanging(string value);
    partial void OnTENNHANVIENChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnMATAIKHOANChanging(string value);
    partial void OnMATAIKHOANChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._TOATHUOCs = new EntitySet<TOATHUOC>(new Action<TOATHUOC>(this.attach_TOATHUOCs), new Action<TOATHUOC>(this.detach_TOATHUOCs));
			this._LICHLAMVIECs = new EntitySet<LICHLAMVIEC>(new Action<LICHLAMVIEC>(this.attach_LICHLAMVIECs), new Action<LICHLAMVIEC>(this.detach_LICHLAMVIECs));
			this._PHIEUHENs = new EntitySet<PHIEUHEN>(new Action<PHIEUHEN>(this.attach_PHIEUHENs), new Action<PHIEUHEN>(this.detach_PHIEUHENs));
			this._PHIEUKHAMs = new EntitySet<PHIEUKHAM>(new Action<PHIEUKHAM>(this.attach_PHIEUKHAMs), new Action<PHIEUKHAM>(this.detach_PHIEUKHAMs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHANVIEN", DbType="NVarChar(30)")]
		public string TENNHANVIEN
		{
			get
			{
				return this._TENNHANVIEN;
			}
			set
			{
				if ((this._TENNHANVIEN != value))
				{
					this.OnTENNHANVIENChanging(value);
					this.SendPropertyChanging();
					this._TENNHANVIEN = value;
					this.SendPropertyChanged("TENNHANVIEN");
					this.OnTENNHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(50)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATAIKHOAN", DbType="VarChar(10)")]
		public string MATAIKHOAN
		{
			get
			{
				return this._MATAIKHOAN;
			}
			set
			{
				if ((this._MATAIKHOAN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._MATAIKHOAN = value;
					this.SendPropertyChanged("MATAIKHOAN");
					this.OnMATAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TOATHUOC", Storage="_TOATHUOCs", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN")]
		public EntitySet<TOATHUOC> TOATHUOCs
		{
			get
			{
				return this._TOATHUOCs;
			}
			set
			{
				this._TOATHUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LICHLAMVIEC", Storage="_LICHLAMVIECs", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN")]
		public EntitySet<LICHLAMVIEC> LICHLAMVIECs
		{
			get
			{
				return this._LICHLAMVIECs;
			}
			set
			{
				this._LICHLAMVIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUHEN", Storage="_PHIEUHENs", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN")]
		public EntitySet<PHIEUHEN> PHIEUHENs
		{
			get
			{
				return this._PHIEUHENs;
			}
			set
			{
				this._PHIEUHENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUKHAM", Storage="_PHIEUKHAMs", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN")]
		public EntitySet<PHIEUKHAM> PHIEUKHAMs
		{
			get
			{
				return this._PHIEUKHAMs;
			}
			set
			{
				this._PHIEUKHAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_NHANVIEN", Storage="_TAIKHOAN", ThisKey="MATAIKHOAN", OtherKey="MATAIKHOAN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MATAIKHOAN = value.MATAIKHOAN;
					}
					else
					{
						this._MATAIKHOAN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOATHUOCs(TOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TOATHUOCs(TOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_LICHLAMVIECs(LICHLAMVIEC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_LICHLAMVIECs(LICHLAMVIEC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUHENs(PHIEUHEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUHENs(PHIEUHEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUKHAMs(PHIEUKHAM entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUKHAMs(PHIEUKHAM entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUHEN")]
	public partial class PHIEUHEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUHEN;
		
		private System.Nullable<System.DateTime> _NGAYKHAM;
		
		private string _KHUNGGIOKHAM;
		
		private string _MANHANVIEN;
		
		private string _VANDESUCKHOE;
		
		private string _TENBENHNHAN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUHENChanging(string value);
    partial void OnMAPHIEUHENChanged();
    partial void OnNGAYKHAMChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKHAMChanged();
    partial void OnKHUNGGIOKHAMChanging(string value);
    partial void OnKHUNGGIOKHAMChanged();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    partial void OnVANDESUCKHOEChanging(string value);
    partial void OnVANDESUCKHOEChanged();
    partial void OnTENBENHNHANChanging(string value);
    partial void OnTENBENHNHANChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public PHIEUHEN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUHEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUHEN
		{
			get
			{
				return this._MAPHIEUHEN;
			}
			set
			{
				if ((this._MAPHIEUHEN != value))
				{
					this.OnMAPHIEUHENChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUHEN = value;
					this.SendPropertyChanged("MAPHIEUHEN");
					this.OnMAPHIEUHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKHAM", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYKHAM
		{
			get
			{
				return this._NGAYKHAM;
			}
			set
			{
				if ((this._NGAYKHAM != value))
				{
					this.OnNGAYKHAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYKHAM = value;
					this.SendPropertyChanged("NGAYKHAM");
					this.OnNGAYKHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHUNGGIOKHAM", DbType="NVarChar(5)")]
		public string KHUNGGIOKHAM
		{
			get
			{
				return this._KHUNGGIOKHAM;
			}
			set
			{
				if ((this._KHUNGGIOKHAM != value))
				{
					this.OnKHUNGGIOKHAMChanging(value);
					this.SendPropertyChanging();
					this._KHUNGGIOKHAM = value;
					this.SendPropertyChanged("KHUNGGIOKHAM");
					this.OnKHUNGGIOKHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="VarChar(10)")]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VANDESUCKHOE", DbType="NVarChar(MAX)")]
		public string VANDESUCKHOE
		{
			get
			{
				return this._VANDESUCKHOE;
			}
			set
			{
				if ((this._VANDESUCKHOE != value))
				{
					this.OnVANDESUCKHOEChanging(value);
					this.SendPropertyChanging();
					this._VANDESUCKHOE = value;
					this.SendPropertyChanged("VANDESUCKHOE");
					this.OnVANDESUCKHOEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBENHNHAN", DbType="NVarChar(30)")]
		public string TENBENHNHAN
		{
			get
			{
				return this._TENBENHNHAN;
			}
			set
			{
				if ((this._TENBENHNHAN != value))
				{
					this.OnTENBENHNHANChanging(value);
					this.SendPropertyChanging();
					this._TENBENHNHAN = value;
					this.SendPropertyChanged("TENBENHNHAN");
					this.OnTENBENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUHEN", Storage="_NHANVIEN", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUHENs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUHENs.Add(this);
						this._MANHANVIEN = value.MANHANVIEN;
					}
					else
					{
						this._MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUKHAM")]
	public partial class PHIEUKHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUKHAM;
		
		private string _MABENHNHAN;
		
		private System.Nullable<int> _TONGTIEN;
		
		private string _MAPHONG;
		
		private string _TRANGTHAIHEN;
		
		private string _MANHANVIEN;
		
		private EntitySet<TOATHUOC> _TOATHUOCs;
		
		private EntityRef<BENHNHAN> _BENHNHAN;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<PHONGKHAM> _PHONGKHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUKHAMChanging(string value);
    partial void OnMAPHIEUKHAMChanged();
    partial void OnMABENHNHANChanging(string value);
    partial void OnMABENHNHANChanged();
    partial void OnTONGTIENChanging(System.Nullable<int> value);
    partial void OnTONGTIENChanged();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnTRANGTHAIHENChanging(string value);
    partial void OnTRANGTHAIHENChanged();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    #endregion
		
		public PHIEUKHAM()
		{
			this._TOATHUOCs = new EntitySet<TOATHUOC>(new Action<TOATHUOC>(this.attach_TOATHUOCs), new Action<TOATHUOC>(this.detach_TOATHUOCs));
			this._BENHNHAN = default(EntityRef<BENHNHAN>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._PHONGKHAM = default(EntityRef<PHONGKHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUKHAM", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUKHAM
		{
			get
			{
				return this._MAPHIEUKHAM;
			}
			set
			{
				if ((this._MAPHIEUKHAM != value))
				{
					this.OnMAPHIEUKHAMChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUKHAM = value;
					this.SendPropertyChanged("MAPHIEUKHAM");
					this.OnMAPHIEUKHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABENHNHAN", DbType="VarChar(10)")]
		public string MABENHNHAN
		{
			get
			{
				return this._MABENHNHAN;
			}
			set
			{
				if ((this._MABENHNHAN != value))
				{
					if (this._BENHNHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABENHNHANChanging(value);
					this.SendPropertyChanging();
					this._MABENHNHAN = value;
					this.SendPropertyChanged("MABENHNHAN");
					this.OnMABENHNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int")]
		public System.Nullable<int> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="VarChar(10)")]
		public string MAPHONG
		{
			get
			{
				return this._MAPHONG;
			}
			set
			{
				if ((this._MAPHONG != value))
				{
					if (this._PHONGKHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHONG = value;
					this.SendPropertyChanged("MAPHONG");
					this.OnMAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAIHEN", DbType="NVarChar(20)")]
		public string TRANGTHAIHEN
		{
			get
			{
				return this._TRANGTHAIHEN;
			}
			set
			{
				if ((this._TRANGTHAIHEN != value))
				{
					this.OnTRANGTHAIHENChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAIHEN = value;
					this.SendPropertyChanged("TRANGTHAIHEN");
					this.OnTRANGTHAIHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="VarChar(10)")]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUKHAM_TOATHUOC", Storage="_TOATHUOCs", ThisKey="MAPHIEUKHAM", OtherKey="MAPHIEUKHAM")]
		public EntitySet<TOATHUOC> TOATHUOCs
		{
			get
			{
				return this._TOATHUOCs;
			}
			set
			{
				this._TOATHUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENHNHAN_PHIEUKHAM", Storage="_BENHNHAN", ThisKey="MABENHNHAN", OtherKey="MABENHNHAN", IsForeignKey=true)]
		public BENHNHAN BENHNHAN
		{
			get
			{
				return this._BENHNHAN.Entity;
			}
			set
			{
				BENHNHAN previousValue = this._BENHNHAN.Entity;
				if (((previousValue != value) 
							|| (this._BENHNHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BENHNHAN.Entity = null;
						previousValue.PHIEUKHAMs.Remove(this);
					}
					this._BENHNHAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUKHAMs.Add(this);
						this._MABENHNHAN = value.MABENHNHAN;
					}
					else
					{
						this._MABENHNHAN = default(string);
					}
					this.SendPropertyChanged("BENHNHAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUKHAM", Storage="_NHANVIEN", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUKHAMs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUKHAMs.Add(this);
						this._MANHANVIEN = value.MANHANVIEN;
					}
					else
					{
						this._MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHAM_PHIEUKHAM", Storage="_PHONGKHAM", ThisKey="MAPHONG", OtherKey="MAPHONG", IsForeignKey=true)]
		public PHONGKHAM PHONGKHAM
		{
			get
			{
				return this._PHONGKHAM.Entity;
			}
			set
			{
				PHONGKHAM previousValue = this._PHONGKHAM.Entity;
				if (((previousValue != value) 
							|| (this._PHONGKHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGKHAM.Entity = null;
						previousValue.PHIEUKHAMs.Remove(this);
					}
					this._PHONGKHAM.Entity = value;
					if ((value != null))
					{
						value.PHIEUKHAMs.Add(this);
						this._MAPHONG = value.MAPHONG;
					}
					else
					{
						this._MAPHONG = default(string);
					}
					this.SendPropertyChanged("PHONGKHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOATHUOCs(TOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUKHAM = this;
		}
		
		private void detach_TOATHUOCs(TOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUKHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGKHAM")]
	public partial class PHONGKHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHONG;
		
		private string _TENPHONG;
		
		private string _VITRI;
		
		private EntitySet<PHIEUKHAM> _PHIEUKHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnTENPHONGChanging(string value);
    partial void OnTENPHONGChanged();
    partial void OnVITRIChanging(string value);
    partial void OnVITRIChanged();
    #endregion
		
		public PHONGKHAM()
		{
			this._PHIEUKHAMs = new EntitySet<PHIEUKHAM>(new Action<PHIEUKHAM>(this.attach_PHIEUKHAMs), new Action<PHIEUKHAM>(this.detach_PHIEUKHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHONG
		{
			get
			{
				return this._MAPHONG;
			}
			set
			{
				if ((this._MAPHONG != value))
				{
					this.OnMAPHONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHONG = value;
					this.SendPropertyChanged("MAPHONG");
					this.OnMAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHONG", DbType="NVarChar(50)")]
		public string TENPHONG
		{
			get
			{
				return this._TENPHONG;
			}
			set
			{
				if ((this._TENPHONG != value))
				{
					this.OnTENPHONGChanging(value);
					this.SendPropertyChanging();
					this._TENPHONG = value;
					this.SendPropertyChanged("TENPHONG");
					this.OnTENPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VITRI", DbType="NVarChar(30)")]
		public string VITRI
		{
			get
			{
				return this._VITRI;
			}
			set
			{
				if ((this._VITRI != value))
				{
					this.OnVITRIChanging(value);
					this.SendPropertyChanging();
					this._VITRI = value;
					this.SendPropertyChanged("VITRI");
					this.OnVITRIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHAM_PHIEUKHAM", Storage="_PHIEUKHAMs", ThisKey="MAPHONG", OtherKey="MAPHONG")]
		public EntitySet<PHIEUKHAM> PHIEUKHAMs
		{
			get
			{
				return this._PHIEUKHAMs;
			}
			set
			{
				this._PHIEUKHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUKHAMs(PHIEUKHAM entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHAM = this;
		}
		
		private void detach_PHIEUKHAMs(PHIEUKHAM entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATAIKHOAN;
		
		private string _TENTAIKHOAN;
		
		private string _MATKHAU;
		
		private string _LOAITAIKHOAN;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATAIKHOANChanging(string value);
    partial void OnMATAIKHOANChanged();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnLOAITAIKHOANChanging(string value);
    partial void OnLOAITAIKHOANChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATAIKHOAN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATAIKHOAN
		{
			get
			{
				return this._MATAIKHOAN;
			}
			set
			{
				if ((this._MATAIKHOAN != value))
				{
					this.OnMATAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._MATAIKHOAN = value;
					this.SendPropertyChanged("MATAIKHOAN");
					this.OnMATAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TENTAIKHOAN
		{
			get
			{
				return this._TENTAIKHOAN;
			}
			set
			{
				if ((this._TENTAIKHOAN != value))
				{
					this.OnTENTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TENTAIKHOAN = value;
					this.SendPropertyChanged("TENTAIKHOAN");
					this.OnTENTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAITAIKHOAN", DbType="NVarChar(10)")]
		public string LOAITAIKHOAN
		{
			get
			{
				return this._LOAITAIKHOAN;
			}
			set
			{
				if ((this._LOAITAIKHOAN != value))
				{
					this.OnLOAITAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._LOAITAIKHOAN = value;
					this.SendPropertyChanged("LOAITAIKHOAN");
					this.OnLOAITAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_NHANVIEN", Storage="_NHANVIENs", ThisKey="MATAIKHOAN", OtherKey="MATAIKHOAN")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUOC")]
	public partial class THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUOC;
		
		private string _TENTHUOC;
		
		private string _QCDONGGOI;
		
		private string _DVT;
		
		private System.Nullable<int> _TONKHO;
		
		private EntitySet<CHITIETTOATHUOC> _CHITIETTOATHUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUOCChanging(string value);
    partial void OnMATHUOCChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    partial void OnQCDONGGOIChanging(string value);
    partial void OnQCDONGGOIChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnTONKHOChanging(System.Nullable<int> value);
    partial void OnTONKHOChanged();
    #endregion
		
		public THUOC()
		{
			this._CHITIETTOATHUOCs = new EntitySet<CHITIETTOATHUOC>(new Action<CHITIETTOATHUOC>(this.attach_CHITIETTOATHUOCs), new Action<CHITIETTOATHUOC>(this.detach_CHITIETTOATHUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUOC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUOC
		{
			get
			{
				return this._MATHUOC;
			}
			set
			{
				if ((this._MATHUOC != value))
				{
					this.OnMATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATHUOC = value;
					this.SendPropertyChanged("MATHUOC");
					this.OnMATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(50)")]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QCDONGGOI", DbType="NVarChar(30)")]
		public string QCDONGGOI
		{
			get
			{
				return this._QCDONGGOI;
			}
			set
			{
				if ((this._QCDONGGOI != value))
				{
					this.OnQCDONGGOIChanging(value);
					this.SendPropertyChanging();
					this._QCDONGGOI = value;
					this.SendPropertyChanged("QCDONGGOI");
					this.OnQCDONGGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(20)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONKHO", DbType="Int")]
		public System.Nullable<int> TONKHO
		{
			get
			{
				return this._TONKHO;
			}
			set
			{
				if ((this._TONKHO != value))
				{
					this.OnTONKHOChanging(value);
					this.SendPropertyChanging();
					this._TONKHO = value;
					this.SendPropertyChanged("TONKHO");
					this.OnTONKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CHITIETTOATHUOC", Storage="_CHITIETTOATHUOCs", ThisKey="MATHUOC", OtherKey="MATHUOC")]
		public EntitySet<CHITIETTOATHUOC> CHITIETTOATHUOCs
		{
			get
			{
				return this._CHITIETTOATHUOCs;
			}
			set
			{
				this._CHITIETTOATHUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETTOATHUOCs(CHITIETTOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = this;
		}
		
		private void detach_CHITIETTOATHUOCs(CHITIETTOATHUOC entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = null;
		}
	}
}
#pragma warning restore 1591
